config/routes.rb
Lightweight::Engine.routes.draw do
  # HACK: Seems like these should be nested resources of the offering, but that's not really practical
  # with the engine's URL scheme. Either way, we need to be able to optionally specify an offering ID.
  resources :activities, :controller => 'lightweight_activities', :constraints => { :id => /\d+/ } do
    resources :pages, :controller => 'interactive_pages', :constraints => { :id => /\d+/ } do
      post 'add_embeddable', :on => :member
    end
  end
  
  # These don't need index or show pages - though there might be something to be said for an
  # index .xml file as a feed for select menus - but they need create-update-delete.
  resources :mw_interactives, :controller => 'mw_interactives', :constraints => { :id => /\d+/ }, :except => :show

  # This is so we can build the InteractiveItem at the same time as the Interactive
  resources :pages, :controller => 'interactive_pages', :constraints => { :id => /\d+/ } do
    resources :mw_interactives, :controller => 'mw_interactives', :constraints => { :id => /\d+/ }, :except => :show
  end

  # best_in_place needs interactive_page_path
  resources :pages, :as => 'interactive_pages', :controller => 'interactive_pages', :constraints => { :id => /\d+/ }, :except => [:new, :create]

  # 'Show' routes including offering_ids
  get "/activities/:id(/:offering_id)" => 'lightweight_activities#show', :as => 'lightweight_activity_show', :constraints => {:id => /\d+/, :offering_id => /\d+/}
  get "/pages/:id(/:offering_id)" => 'interactive_pages#show', :as => 'interactive_page_show', :constraints => { :id => /\d+/, :offering_id => /\d+/ }
  get "/activities/:activity_id/pages/:id(/:offering_id)" => 'interactive_pages#show', :as => 'activity_page_offering_show', :constraints => { :id => /\d+/, :offering_id => /\d+/, :activity_id => /\d+/ }

  # This route didn't work as a nested resource
  post "/pages/:id/remove_embeddable/:embeddable_id" => 'interactive_pages#remove_embeddable', :as => 'page_remove_embeddable', :constraints => { :id => /\d+/, :embeddable_id => /\d+/ }
end

app/models/lightweight/interactive_item.rb
module Lightweight
  class InteractiveItem < ActiveRecord::Base
    attr_accessible :interactive, :interactive_page, :position

    belongs_to :interactive_page
    belongs_to :interactive, :polymorphic => true
  end
end

app/models/lightweight/interactive_page.rb
module Lightweight
  class InteractivePage < ActiveRecord::Base
    attr_accessible :lightweight_activity, :name, :position, :user, :text, :theme, :sidebar

    belongs_to :lightweight_activity, :class_name => 'Lightweight::LightweightActivity'

    has_many :interactive_items, :order => :position

    def interactives
      self.interactive_items.collect{|ii| ii.interactive}
    end

    has_many :page_items, :order => :position
    def embeddables
      self.page_items.collect{|qi| qi.embeddable}
    end

    def add_interactive(interactive, position = nil)
      Lightweight::InteractiveItem.create!(:interactive_page => self, :interactive => interactive, :position => (position || self.interactive_items.size))
    end

    def add_embeddable(embeddable, position = nil)
      Lightweight::PageItem.create!(:interactive_page => self, :embeddable => embeddable, :position => (position || self.page_items.size))
    end
  end
end

app/models/lightweight/lightweight_activity.rb
module Lightweight
  class LightweightActivity < ActiveRecord::Base
    attr_accessible :name, :publication_status, :user_id, :pages, :related, :description

    belongs_to :user, :class_name => '::User' # Author

    has_many :pages, :foreign_key => 'lightweight_activity_id', :class_name => 'Lightweight::InteractivePage', :order => :position

    has_many :offerings, :dependent => :destroy, :as => :runnable, :class_name => "Portal::Offering"

    def run_format
      :run_html
    end
  end
end

app/controllers/lightweight/application_controller.rb
module Lightweight
  class ApplicationController < ActionController::Base

    # Borrowed methods from lib/authenticated_system.rb, which we've had little luck reaching from the engine.
    def current_user
      @current_user ||= (login_from_session || login_from_basic_auth || login_from_cookie) unless @current_user == false
    end

    # Store the given user id in the session.
    def current_user=(new_user)
      session[:user_id] = new_user ? new_user.id : nil
      @current_user = new_user || false
    end

    # Called from #current_user.  First attempt to login by the user id stored in the session.
    def login_from_session
      if (defined? ::User) == 'constant'
        self.current_user = ::User.find_by_id(session[:user_id]) if session[:user_id]
      else
        return false
      end
    end

    # Called from #current_user.  Now, attempt to login by basic authentication information.
    def login_from_basic_auth
      if (defined? ::User) == 'constant'
        authenticate_with_http_basic do |login, password|
            self.current_user = ::User.authenticate(login, password)
        end
      else
        return false
      end
    end

    # Called from #current_user.  Finally, attempt to login by an expiring token in the cookie.
    # for the paranoid: we _should_ be storing user_token = hash(cookie_token, request IP)
    def login_from_cookie
      if (defined? ::User) == 'constant'
        user = cookies[:auth_token] && ::User.find_by_remember_token(cookies[:auth_token])
        if user && user.remember_token?
          self.current_user = user
          handle_remember_cookie! false # freshen cookie token (keeping date)
          self.current_user
        end
      else
        return false
      end
    end
  end
end

app/controllers/lightweight/interactive_page_controller.rb
require_dependency "lightweight/application_controller"

module Lightweight
  class InteractivePageController < ApplicationController

    def show
      @page = Lightweight::InteractivePage.find(params[:id])
      @activity = @page.lightweight_activity
      # TODO: Select the offering properly rather than hard-wiring it.
      if (params[:offering_id])
        begin
          @offering = @activity.offerings.find(params[:offering_id])
        rescue
          # HACK: This is a bad data situation, where the page comes from a
          # different activity than the runnable for the offering.
          # The correct response should be some kind of error page, I think.
          @offering = @activity.offerings.first
        end
      else
        @offering = @activity.offerings.first
      end
      if @offering
        @learner = setup_portal_student
      end
      @all_pages = @activity.pages
      current_idx = @all_pages.index(@page)
      @previous_page = (current_idx > 0) ? @all_pages[current_idx-1] : nil
      @next_page = (current_idx < (@all_pages.size-1)) ? @all_pages[current_idx+1] : nil

      respond_to do |format|
        format.html
        format.xml
        format.run_html { render :show }
      end
    end

    private
    # This is borrowed from the Portal::Offerings controller and should perhaps be more generalized.
    def setup_portal_student
      learner = nil
      # HACK: AuthenticatedSystem isn't accessible from the engine, so we need to find current_user directly. I don't much like this.
      if !session[:user_id].blank? && (defined? ::User) == 'constant'
        portal_student = ::User.find(session[:user_id]).portal_student
        # create a learner for the user if one doesn't exist
        learner = @offering.find_or_create_learner(portal_student)
      end
      learner
    end
  end
end

app/controllers/lightweight/interactive_pages_controller.rb
require_dependency "lightweight/application_controller"

module Lightweight
  class InteractivePagesController < ApplicationController
    before_filter :set_page, :except => [:new, :create]

    def show
      # TODO: Select the offering properly rather than hard-wiring it.
      if (params[:offering_id])
        begin
          @offering = @activity.offerings.find(params[:offering_id])
        rescue
          # HACK: This is a bad data situation, where the page comes from a
          # different activity than the runnable for the offering.
          # The correct response should be some kind of error page, I think.
          @offering = @activity.offerings.first
        end
      else
        @offering = @activity.offerings.first
      end
      if @offering
        @learner = setup_portal_student
      end
      @all_pages = @activity.pages
      current_idx = @all_pages.index(@page)
      @previous_page = (current_idx > 0) ? @all_pages[current_idx-1] : nil
      @next_page = (current_idx < (@all_pages.size-1)) ? @all_pages[current_idx+1] : nil

      respond_to do |format|
        format.html
        format.xml
        format.run_html { render :show }
      end
    end

    def new
      # There's really nothing to do here; we can go through #create and skip on ahead to #edit.
      create
    end

    def create
      @activity = Lightweight::LightweightActivity.find(params[:activity_id])
      @page = Lightweight::InteractivePage.create!(:lightweight_activity => @activity)
      flash[:notice] = "A new page was added to #{@activity.name}"
      redirect_to edit_activity_page_path(@activity, @page)
    end

    def edit
    end

    def update
      respond_to do |format|
        if @page.update_attributes(params[:interactive_page])
          format.html do
            flash[:notice] = "Page #{@page.name} was updated."
            redirect_to edit_activity_page_path(@activity, @page)
          end
          format.json { respond_with_bip @page }
        else
          format.html do
            flash[warning] = "There was a problem updating Page #{@page.name}."
            redirect_to edit_activity_page_path(@activity, @page)
          end
          format.json { respond_with_bip @page }
        end
      end
    end

    def destroy
      if @page.delete
        flash[:notice] = "Page #{@page.name} was deleted."
        redirect_to edit_activity_path(@activity)
      else
        flash[:warning] = "There was a problem deleting page #{@page.name}."
        redirect_to edit_activity_path(@activity)
      end
    end

    def add_embeddable
      e = params[:embeddable_type].constantize.create!
      @page.add_embeddable(e)
      redirect_to edit_activity_page_path(@activity, @page)
    end

    def remove_embeddable
      Lightweight::PageItem.find_by_interactive_page_id_and_embeddable_id(params[:id], params[:embeddable_id]).destroy
      redirect_to edit_activity_page_path(@activity, @page)
    end

    private
    def set_page
      if params[:activity_id]
        @activity = Lightweight::LightweightActivity.find(params[:activity_id], :include => :pages)
        @page = @activity.pages.find(params[:id])
        # TODO: Exception handling if the ID'd Page doesn't belong to the ID'd Activity
      else
        # I don't like this method much.
        @page = Lightweight::InteractivePage.find(params[:id], :include => :lightweight_activity)
        @activity = @page.lightweight_activity
      end
    end

    # This is borrowed from the Portal::Offerings controller and should perhaps be more generalized.
    def setup_portal_student
      learner = nil
      if current_user
        portal_student = current_user.portal_student
        # create a learner for the user if one doesn't exist
        learner = @offering.find_or_create_learner(portal_student)
      end
      learner
    end
  end
end

app/controllers/lightweight/lightweight_activities_controller.rb
require_dependency "lightweight/application_controller"

module Lightweight
  class LightweightActivitiesController < ApplicationController
    before_filter :set_activity, :except => [:index, :new, :create]

    def index
      if current_user.blank?
        @activities ||= Lightweight::LightweightActivity.find(:all)
      else
        @activities = Lightweight::LightweightActivity.find_all_by_user_id(current_user.id)
      end
    end

    def show
      # If we're given an offering ID, use that to set the offering; otherwise just take the first one.
      @offering = params[:offering_id] ? Portal::Offering.find(params[:offering_id]) : @activity.offerings.first
      redirect_to activity_page_offering_show_path(@activity, @activity.pages.first, @offering)
    end

    def new
      @activity = Lightweight::LightweightActivity.new()
    end

    def create
      @activity = Lightweight::LightweightActivity.create(params[:lightweight_activity])
      if current_user
        @activity.user = current_user
      end
      if @activity.save
        flash[:notice] = "Lightweight Activity #{@activity.name} was created."
        redirect_to edit_activity_path(@activity)
      else
        flash[:warning] = "There was a problem creating the new Lightweight Activity."
        render :new
      end
    end

    def edit
    end

    def update
      if @activity.update_attributes(params[:lightweight_activity])
        flash[:notice] = "Activity #{@activity.name} was updated."
        redirect_to edit_activity_path(@activity)
      else
        flash[:warning] = "There was a problem updating activity #{@activity.name}."
        redirect_to edit_activity_path(@activity)
      end
    end

    def destroy
      if @activity.delete
        flash[:notice] = "Activity #{@activity.name} was deleted."
        redirect_to activities_path
      else
        flash[:warning] = "There was a problem deleting activity #{@activity.name}."
        redirect_to edit_activity_path(@activity)
      end
    end

    private
    def set_activity
      @activity = Lightweight::LightweightActivity.find(params[:id])
    end
  end
end

app/controllers/lightweight/lightweight_activity_controller.rb
require_dependency "lightweight/application_controller"

module Lightweight
  class LightweightActivityController < ApplicationController
    def show
      @activity = Lightweight::LightweightActivity.find(params[:id])
      # If we're given an offering ID, use that to set the offering; otherwise just take the first one.
      @offering = params[:offering_id] ? Portal::Offering.find(params[:offering_id]) : @activity.offerings.first
      redirect_to interactive_page_show_url(@activity.pages.first, @offering)
    end
  end
end

app/helpers/lightweight/application_helper.rb
module Lightweight
  module ApplicationHelper
    def edit_menu_for(component, form, options={:omit_cancel => true}, scope=false)
      component = (component.respond_to? :embeddable) ? component.embeddable : component
      capture_haml do
        haml_tag :div, :class => 'action_menu' do
          haml_tag :div, :class => 'action_menu_header_left' do
            haml_tag(:h3,{:class => 'menu'}) do
              haml_concat title_for_component(component, :id_prefix => 'edit')
            end
          end
          haml_tag :div, :class => 'action_menu_header_right' do
            haml_tag :ul, {:class => 'menu'} do
              #if (component.changeable?(current_user))
              haml_tag(:li, {:class => 'menu'}) { haml_concat form.submit("Save") }
              haml_tag(:li, {:class => 'menu'}) { haml_concat form.submit("Cancel") } unless options[:omit_cancel]
              #end
            end
          end
        end
      end
    end

    def title_for_component(component, options={})
      title = name_for_component(component, options)
      id = dom_id_for(component, options[:id_prefix], :title)
#      if ::Rails.env == "development" || @current_user.has_role?('admin')
      if false # TODO: Get this working correctly
        "<span id=#{id} class='component_title'>#{title}</span><span class='dev_note'> #{link_to(component.id, component)}</span>"
      else
        "<span id=#{id} class='component_title'>#{title}</span>"
      end
    end

    def name_for_component(component, options={})
      if options[:display_name]
        return options[:display_name]
      end
      name = ''
      unless options[:hide_component_name]
        if component.class.respond_to? :display_name
          name << component.class.display_name
        else
          name << component.class.name.humanize
        end
        if component.respond_to? :display_type
          name = "#{component.display_type} #{name}"
        end
        name << ': '
      end
      default_name = ''
      if component.class.respond_to?(:default_value)
        default_name = component.class.default_value('name')
      end
      name << case
        when component.id.nil? then "(new)"
        when component.name == default_name then ''
        when component.name then component.name
        else ''
      end
    end

    def dom_id_for(component, *optional_prefixes)
      optional_prefixes.flatten!
      optional_prefixes.compact! unless optional_prefixes.empty?
      prefix = ''
      optional_prefixes.each { |p| prefix << "#{p.to_s}_" }
      class_name = component.class.name.underscore
      if component.is_a?(ActiveRecord::Base)
        id = component.id || Time.now.to_i
      else
        # this will be a temporary id, so it seems unlikely that these type of ids
        # should be really be generated, however there are some parts of the code
        # calling dom_id_for and passing a form object for example
        id = component.object_id
      end
      id_string = id.to_s
      "#{prefix}#{class_name}_#{id_string}"
    end
  end
end

app/helpers/lightweight/lightweight_activity_helper.rb
module Lightweight
  module LightweightActivityHelper
    def toggle_all(label='all', id_prefix='details_')
      link_to_function("show/hide #{label}", "$$('div[id^=#{id_prefix}]').each(function(d) { Effect.toggle(d,'blind', {duration:0.25}) });")
    end
  end
end

app/helpers/lightweight/mw_interactives_helper.rb
module Lightweight
  module MwInteractivesHelper
  end
end

app/views/lightweight/interactive_pages/_show.html.haml
- next_page = nil unless defined?(next_page)
- previous_page = nil unless defined?(previous_page)
%div{:class => ["content", page.theme]}
  .page-nav
    - if previous_page
      - if @offering
        %a{:class => 'previous', :href => activity_page_offering_show_path(previous_page.lightweight_activity, previous_page, @offering)}
          ! &nbsp;
      -else
        %a{:class => 'previous', :href => activity_page_path(previous_page.lightweight_activity, previous_page)}
          ! &nbsp;
    - else
      %a{:class => 'previous disabled'}
        ! &nbsp;
    - page_counter = 1
    - all_pages.each do |p|
      - if @offering
        = link_to page_counter, activity_page_offering_show_path(p.lightweight_activity, p, @offering), :class => (p === page) ? 'active' : ''
      - else
        = link_to page_counter, activity_page_path(p.lightweight_activity, p), :class => (p === page) ? 'active' : ''
      - page_counter = page_counter + 1
    - if next_page
      - if @offering
        %a{:class => 'next', :href => activity_page_offering_show_path(next_page.lightweight_activity, next_page, @offering)}
          ! &nbsp;
      -else
        %a{:class => 'next', :href => activity_page_path(next_page.lightweight_activity, next_page)}
          ! &nbsp;
    - else
      %a{:class => 'next disabled'}
        ! &nbsp;
  %h1.title
    = page.lightweight_activity.name
  %p.question= page.name
  .text
    %p.instructions= page.text
    .questions
      - if @offering
        = form_tag(main_app.answers_portal_offering_path(@offering)) do
          - page.embeddables.each do |e|
            - e_type = e.class.name.underscore
            = render :partial => "#{e_type}/lightweight", :locals => {:embeddable => e}
          = submit_tag "Save Answers"
      - else
        - page.embeddables.each do |e|
          - e_type = e.class.name.underscore
          = render :partial => "#{e_type}/lightweight", :locals => {:embeddable => e}
  .other
    - page.interactives.each do |interactive|
      - i_type = interactive.class.name.underscore
      = render :partial => "#{i_type.pluralize}/show", :locals => {:interactive => interactive}
  - if page.sidebar
    .sidebar
      != page.sidebar
  - if !next_page
    .related
      != page.lightweight_activity.related
  - if page.interactives
    #embed
    #share

app/views/lightweight/interactive_pages/edit.html.haml
=# TODO: Deal with pagination. This seems like a good place to handle "Add page."
- next_page = nil unless defined?(next_page)
- previous_page = nil unless defined?(previous_page)
%div{:class => ["content", @page.theme]}
  .page-nav
    - if previous_page
      %a{:class => 'previous', :href => edit_activity_page_path(@activity, previous_page)}
        ! &nbsp;
    - else
      %a{:class => 'previous disabled'}
        ! &nbsp;
    - page_counter = 1
    - @activity.pages.each do |p|
      = link_to page_counter, edit_activity_page_path(@activity, p), :class => (p === @page) ? 'active' : ''
      - page_counter = page_counter + 1
    - if next_page
      %a{:class => 'next', :href => edit_activity_page_path(@activity, next_page)}
        ! &nbsp;
    - else
      = link_to '+', new_activity_page_path(@activity), {:title => "Add another page to #{@activity.name}", :class => 'next'}

  %h1.title
    = @activity.name
  %p.question
    Editing
    = best_in_place @page, :name, :type => :input, :nil => 'page name (click to edit)'
    = field_set_tag 'Page Appearance' do
      = best_in_place @page, :theme, :type => :input
    .text
      %p.instructions
        = best_in_place @page, :text, :type => :textarea, :nil => "Instructions (click to edit)"
      = form_tag :controller => 'interactive_pages', :action => 'add_embeddable' do
        = select_tag :embeddable_type, options_for_select(Lightweight::SUPPORTED_EMBEDDABLES.map { |e| [e[/::(\w+)$/,1], e] })
        = submit_tag 'Add Embeddable'
      .questions
        - @page.embeddables.each do |e|
          - e_type = e.class.name.underscore
          = render :partial => "#{e_type}/author", :locals => { :embeddable => e, :page => @page }
    .other
      - @page.interactives.each do |interactive|
        - i_type = interactive.class.name.underscore
        = render :partial => "#{i_type.pluralize}/author", :locals => {:interactive => interactive}
      = link_to "Add interactive", new_page_mw_interactive_path(@page)
    .sidebar
      = best_in_place @page, :sidebar, :type => :textarea, :rows => 5, :nil => 'Sidebar text (click to edit)'
    - if @page.interactives
      #embed
      #share

  =# javascript_tag("focus_first_field();");

  %ul.tasks
    %li= link_to "See this page", activity_page_path(@activity, @page), :target => 'new'
    %li= link_to "Return to editing #{@activity.name}", edit_activity_path(@activity)
    %li= link_to "Add another page to #{@activity.name}", new_activity_page_path(@activity)
    %li= link_to "All activities", activities_path

app/views/lightweight/interactive_pages/show.html.haml
-# TODO: This should become the authoring view
= render :partial => 'lightweight/interactive_pages/show', :locals => {:page => @page, :previous_page => @previous_page, :next_page => @next_page, :all_pages => @all_pages}

app/views/lightweight/interactive_pages/show.run_html.haml
-# This is the runtime view
= render :partial => 'lightweight/interactive_pages/show', :locals => {:page => @page, :previous_page => @previous_page, :next_page => @next_page, :all_pages => @all_pages}